What_to_cook_today/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from userextend.forms import AuthenticationNewForm, PasswordChangeNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    path('', include('ingredients.urls')),
    path('', include('recipies.urls')),
    path('', include('shopping.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path("password_change/", views.PasswordChangeView.as_view(form_class=PasswordChangeNewForm), name="password_change"),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),

]

about/urls.py
from django.urls import path

from about import views

urlpatterns = [
    path('', views.about_page_view, name='about_page'),

]

ingredients/models.py
from django.contrib.auth.models import User
from django.db import models


class Ingredient(models.Model):
    name = models.CharField(max_length=30)
    category = models.CharField(max_length=30)
    description = models.TextField(max_length=270)

    def __str__(self):
        return f'{self.name} {self.category} {self.description}'


class Grocery(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'


class UserShoppingList(models.Model):
    id = models.indexes
    user_id = models.IntegerField
    username = models.CharField(max_length=100)
    shoppingList = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.id} {self.user_id} {self.username} {self.shoppingList}'


class UserItemList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Property(models.Model):
    class Meta:
        verbose_name_plural = "properties"

    name = models.CharField(max_length=30)
    category = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

recipies/models.py
from django.db import models


class Recipie(models.Model):
    name = models.CharField(max_length=30)
    category = models.CharField(max_length=30)
    ingredients = models.CharField(max_length=270)
    main_ingredients = models.CharField(max_length=270)
    description = models.TextField(max_length=300)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} {self.category}'

shopping/models.py
from django.db import models


class Store(models.Model):
    name = models.CharField(max_length=200)
    location = models.TextField(max_length=200)
    category = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=270)

    def __str__(self):
        return f'{self.name}'


class ShoppingList(models.Model):
    category = models.CharField(max_length=200)
    ingredient = models.CharField(max_length=270)

    def __str__(self):
        return f'{self.category} {self.ingredient}'

templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">


</head>
<body id="body">
{% include 'navbar.html' %}


{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
        integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% load i18n %}
<title>{% trans "This is the title." %}</title>
{% blocktrans %}This string will have {{ value }} inside.{% endblocktrans %}

<ul id="nav">
    <a href='/'> {% trans "Ingredients" %} </a>
    <a href="{% url 'list-of-ingredients' %}" class="> {% trans "List of ingredients" %} </a>
</ul>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">What to cook today</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'about_page' %}">About</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Ingredients
                    </a>

                    <ul class="dropdown-menu">
                        {% if perms.ingredient.add_ingredient %}
                            <li><a class="dropdown-item" href="{% url 'create-ingredient' %}">Add new
                                ingredient</a>
                            </li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'list-of-ingredients' %}">List of
                            ingredients</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'grocery-list' %}">Grocery list</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Recipes
                    </a>

                    <ul class="dropdown-menu">
                        {% if perms.recipies.add_recipie %}
                        <li><a class="dropdown-item" href="{% url 'create-recipie' %}">Add new
                            recipe</a>
                        </li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'list-of-recipies' %}">List of
                            recipes</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Shopping
                    </a>

                    <ul class="dropdown-menu">
                        {% if perms.shopping.add_store %}
                        <li><a class="dropdown-item" href="{% url 'create-store' %}">Add new store</a>
                        </li>
                        {% endif %}

                        <li><a class="dropdown-item" href="{% url 'list-of-stores' %}">List of stores</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    {{ user.username }}
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                </ul>
            </div>
            <a href='{% url 'login' %}' class="btn btn-outline-secondary">Login</a>
            <a href="{% url 'create-user' %}" class="btn btn-outline-secondary">Sign up</a>
        </div>
    </div>
</nav>